- name: Install Java and Kafka
  hosts: ec2
  become: yes
  vars:
    kafka_version: "3.9.0"
    scala_version: "2.13"
    kafka_tgz: "kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    kafka_url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/{{ kafka_tgz }}"
    kafka_extract_dir: "kafka_{{ scala_version }}-{{ kafka_version }}"

  tasks:
    # Installing Java
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    # Installing Kafka-connect
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download Kafka archive
      get_url:
        url: "{{ kafka_url }}"
        dest: "/tmp/{{ kafka_tgz }}"

    - name: Extract Kafka archive
      unarchive:
        src: "/tmp/{{ kafka_tgz }}"
        dest: "/tmp"
        remote_src: yes

    - name: Move Kafka to /opt
      command: mv /tmp/{{ kafka_extract_dir }} /opt/kafka
      args:
        creates: /opt/kafka

    # Creating kafka user
    - name: Create kafka user
      user:
        name: kafka
        system: yes
        shell: /usr/sbin/nologin
        home: /opt/kafka

    - name: Set ownership of /opt/kafka
      file:
        path: /opt/kafka
        owner: kafka
        group: kafka
        recurse: yes

    # Creating systemd unit file for Zookeeper
    - name: Upload zookeeper.service to systemd
      copy:
        src: zookeeper.service  
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: '0644'
      notify: Reload systemd

    - name: Enable and start Zookeeper
      systemd:
        name: zookeeper
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec